server:
  port: 8006



spring:
  application:
    name: consul-provider-payment
    # consul 的注册中心
  cloud:
    consul:
      host: 134.175.82.194
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true