server:
  port: 80

spring:
  application:
    name: cloud-order-service

# 踩坑1：先启动7001、7002；再启动8001、最后启动80
eureka:
  client:
    register-with-eureka: true
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true